                                                                                     index_sql                                                                                     
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE UNIQUE INDEX audit_log_entries_pkey ON auth.audit_log_entries USING btree (id);
 CREATE INDEX audit_logs_instance_id_idx ON auth.audit_log_entries USING btree (instance_id);
 CREATE INDEX flow_state_created_at_idx ON auth.flow_state USING btree (created_at DESC);
 CREATE UNIQUE INDEX flow_state_pkey ON auth.flow_state USING btree (id);
 CREATE INDEX idx_auth_code ON auth.flow_state USING btree (auth_code);
 CREATE INDEX idx_user_id_auth_method ON auth.flow_state USING btree (user_id, authentication_method);
 CREATE INDEX identities_email_idx ON auth.identities USING btree (email text_pattern_ops);
 CREATE UNIQUE INDEX identities_pkey ON auth.identities USING btree (id);
 CREATE UNIQUE INDEX identities_provider_id_provider_unique ON auth.identities USING btree (provider_id, provider);
 CREATE INDEX identities_user_id_idx ON auth.identities USING btree (user_id);
 CREATE UNIQUE INDEX instances_pkey ON auth.instances USING btree (id);
 CREATE UNIQUE INDEX amr_id_pk ON auth.mfa_amr_claims USING btree (id);
 CREATE UNIQUE INDEX mfa_amr_claims_session_id_authentication_method_pkey ON auth.mfa_amr_claims USING btree (session_id, authentication_method);
 CREATE INDEX mfa_challenge_created_at_idx ON auth.mfa_challenges USING btree (created_at DESC);
 CREATE UNIQUE INDEX mfa_challenges_pkey ON auth.mfa_challenges USING btree (id);
 CREATE INDEX factor_id_created_at_idx ON auth.mfa_factors USING btree (user_id, created_at);
 CREATE UNIQUE INDEX mfa_factors_last_challenged_at_key ON auth.mfa_factors USING btree (last_challenged_at);
 CREATE UNIQUE INDEX mfa_factors_pkey ON auth.mfa_factors USING btree (id);
 CREATE UNIQUE INDEX mfa_factors_user_friendly_name_unique ON auth.mfa_factors USING btree (friendly_name, user_id) WHERE (TRIM(BOTH FROM friendly_name) <> ''::text);
 CREATE INDEX mfa_factors_user_id_idx ON auth.mfa_factors USING btree (user_id);
 CREATE UNIQUE INDEX unique_phone_factor_per_user ON auth.mfa_factors USING btree (user_id, phone);
 CREATE INDEX oauth_clients_client_id_idx ON auth.oauth_clients USING btree (client_id);
 CREATE UNIQUE INDEX oauth_clients_client_id_key ON auth.oauth_clients USING btree (client_id);
 CREATE INDEX oauth_clients_deleted_at_idx ON auth.oauth_clients USING btree (deleted_at);
 CREATE UNIQUE INDEX oauth_clients_pkey ON auth.oauth_clients USING btree (id);
 CREATE UNIQUE INDEX one_time_tokens_pkey ON auth.one_time_tokens USING btree (id);
 CREATE INDEX one_time_tokens_relates_to_hash_idx ON auth.one_time_tokens USING hash (relates_to);
 CREATE INDEX one_time_tokens_token_hash_hash_idx ON auth.one_time_tokens USING hash (token_hash);
 CREATE UNIQUE INDEX one_time_tokens_user_id_token_type_key ON auth.one_time_tokens USING btree (user_id, token_type);
 CREATE INDEX refresh_tokens_instance_id_idx ON auth.refresh_tokens USING btree (instance_id);
 CREATE INDEX refresh_tokens_instance_id_user_id_idx ON auth.refresh_tokens USING btree (instance_id, user_id);
 CREATE INDEX refresh_tokens_parent_idx ON auth.refresh_tokens USING btree (parent);
 CREATE UNIQUE INDEX refresh_tokens_pkey ON auth.refresh_tokens USING btree (id);
 CREATE INDEX refresh_tokens_session_id_revoked_idx ON auth.refresh_tokens USING btree (session_id, revoked);
 CREATE UNIQUE INDEX refresh_tokens_token_unique ON auth.refresh_tokens USING btree (token);
 CREATE INDEX refresh_tokens_updated_at_idx ON auth.refresh_tokens USING btree (updated_at DESC);
 CREATE UNIQUE INDEX saml_providers_entity_id_key ON auth.saml_providers USING btree (entity_id);
 CREATE UNIQUE INDEX saml_providers_pkey ON auth.saml_providers USING btree (id);
 CREATE INDEX saml_providers_sso_provider_id_idx ON auth.saml_providers USING btree (sso_provider_id);
 CREATE INDEX saml_relay_states_created_at_idx ON auth.saml_relay_states USING btree (created_at DESC);
 CREATE INDEX saml_relay_states_for_email_idx ON auth.saml_relay_states USING btree (for_email);
 CREATE UNIQUE INDEX saml_relay_states_pkey ON auth.saml_relay_states USING btree (id);
 CREATE INDEX saml_relay_states_sso_provider_id_idx ON auth.saml_relay_states USING btree (sso_provider_id);
 CREATE UNIQUE INDEX schema_migrations_pkey ON auth.schema_migrations USING btree (version);
 CREATE INDEX sessions_not_after_idx ON auth.sessions USING btree (not_after DESC);
 CREATE UNIQUE INDEX sessions_pkey ON auth.sessions USING btree (id);
 CREATE INDEX sessions_user_id_idx ON auth.sessions USING btree (user_id);
 CREATE INDEX user_id_created_at_idx ON auth.sessions USING btree (user_id, created_at);
 CREATE UNIQUE INDEX sso_domains_domain_idx ON auth.sso_domains USING btree (lower(domain));
 CREATE UNIQUE INDEX sso_domains_pkey ON auth.sso_domains USING btree (id);
 CREATE INDEX sso_domains_sso_provider_id_idx ON auth.sso_domains USING btree (sso_provider_id);
 CREATE UNIQUE INDEX sso_providers_pkey ON auth.sso_providers USING btree (id);
 CREATE UNIQUE INDEX sso_providers_resource_id_idx ON auth.sso_providers USING btree (lower(resource_id));
 CREATE INDEX sso_providers_resource_id_pattern_idx ON auth.sso_providers USING btree (resource_id text_pattern_ops);
 CREATE UNIQUE INDEX confirmation_token_idx ON auth.users USING btree (confirmation_token) WHERE ((confirmation_token)::text !~ '^[0-9 ]*$'::text);
 CREATE UNIQUE INDEX email_change_token_current_idx ON auth.users USING btree (email_change_token_current) WHERE ((email_change_token_current)::text !~ '^[0-9 ]*$'::text);
 CREATE UNIQUE INDEX email_change_token_new_idx ON auth.users USING btree (email_change_token_new) WHERE ((email_change_token_new)::text !~ '^[0-9 ]*$'::text);
 CREATE UNIQUE INDEX reauthentication_token_idx ON auth.users USING btree (reauthentication_token) WHERE ((reauthentication_token)::text !~ '^[0-9 ]*$'::text);
 CREATE UNIQUE INDEX recovery_token_idx ON auth.users USING btree (recovery_token) WHERE ((recovery_token)::text !~ '^[0-9 ]*$'::text);
 CREATE UNIQUE INDEX users_email_partial_key ON auth.users USING btree (email) WHERE (is_sso_user = false);
 CREATE INDEX users_instance_id_email_idx ON auth.users USING btree (instance_id, lower((email)::text));
 CREATE INDEX users_instance_id_idx ON auth.users USING btree (instance_id);
 CREATE INDEX users_is_anonymous_idx ON auth.users USING btree (is_anonymous);
 CREATE UNIQUE INDEX users_phone_key ON auth.users USING btree (phone);
 CREATE UNIQUE INDEX users_pkey ON auth.users USING btree (id);
 CREATE UNIQUE INDEX calculation_history_pkey ON public.calculation_history USING btree (id);
 CREATE INDEX idx_calculation_history_created_at ON public.calculation_history USING btree (created_at);
 CREATE INDEX idx_calculation_history_job_type ON public.calculation_history USING btree (job_type);
 CREATE INDEX idx_calculation_history_user_id ON public.calculation_history USING btree (user_id);
 CREATE UNIQUE INDEX custom_scraping_urls_pkey ON public.custom_scraping_urls USING btree (id);
 CREATE INDEX idx_custom_scraping_urls_auto_scraping ON public.custom_scraping_urls USING btree (auto_scraping_enabled, next_auto_scrape_at) WHERE (auto_scraping_enabled = true);
 CREATE INDEX idx_custom_scraping_urls_material_auto ON public.custom_scraping_urls USING btree (material_type, auto_scraping_enabled) WHERE (auto_scraping_enabled = true);
 CREATE UNIQUE INDEX material_prices_material_type_key ON public.material_prices USING btree (material_type);
 CREATE UNIQUE INDEX material_prices_pkey ON public.material_prices USING btree (id);
 CREATE INDEX idx_scraping_history_scraped_at ON public.scraping_history USING btree (scraped_at);
 CREATE INDEX idx_scraping_history_url_id ON public.scraping_history USING btree (url_id);
 CREATE UNIQUE INDEX scraping_history_pkey ON public.scraping_history USING btree (id);
 CREATE INDEX idx_scraping_sources_active ON public.scraping_sources USING btree (is_active);
 CREATE UNIQUE INDEX scraping_sources_name_key ON public.scraping_sources USING btree (name);
 CREATE UNIQUE INDEX scraping_sources_pkey ON public.scraping_sources USING btree (id);
 CREATE UNIQUE INDEX url_history_pkey ON public.url_history USING btree (id);
 CREATE UNIQUE INDEX messages_pkey ON ONLY realtime.messages USING btree (id, inserted_at);
 CREATE UNIQUE INDEX schema_migrations_pkey ON realtime.schema_migrations USING btree (version);
 CREATE INDEX ix_realtime_subscription_entity ON realtime.subscription USING btree (entity);
 CREATE UNIQUE INDEX pk_subscription ON realtime.subscription USING btree (id);
 CREATE UNIQUE INDEX subscription_subscription_id_entity_filters_key ON realtime.subscription USING btree (subscription_id, entity, filters);
 CREATE UNIQUE INDEX bname ON storage.buckets USING btree (name);
 CREATE UNIQUE INDEX buckets_pkey ON storage.buckets USING btree (id);
 CREATE UNIQUE INDEX migrations_name_key ON storage.migrations USING btree (name);
 CREATE UNIQUE INDEX migrations_pkey ON storage.migrations USING btree (id);
 CREATE UNIQUE INDEX bucketid_objname ON storage.objects USING btree (bucket_id, name);
 CREATE INDEX idx_objects_bucket_id_name ON storage.objects USING btree (bucket_id, name COLLATE "C");
 CREATE INDEX name_prefix_search ON storage.objects USING btree (name text_pattern_ops);
 CREATE UNIQUE INDEX objects_pkey ON storage.objects USING btree (id);
 CREATE INDEX idx_multipart_uploads_list ON storage.s3_multipart_uploads USING btree (bucket_id, key, created_at);
 CREATE UNIQUE INDEX s3_multipart_uploads_pkey ON storage.s3_multipart_uploads USING btree (id);
 CREATE UNIQUE INDEX s3_multipart_uploads_parts_pkey ON storage.s3_multipart_uploads_parts USING btree (id);
(97 rows)

